### ISSUE TITLE
cannot pass delta="fossil" argument in client new_subscription method

### ISSUE THREAD

**Issue by patterniha** [vovadenisov/centrifuge-python#23]
in example.py file say when you create new subscription (client.new_subscription):
--- # you can pass `delta="fossil"` too

but new_subscription function does not  have "delta" argument.
so when you try pass delta argument to new_subscription (client.new_subscription(..., delta="fossil") throw an error:
--- Client.new_subscription() got an unexpected keyword argument 'delta'

how can pass delta="fossil"to new_subscription and how can i enable fossil algorithm for receive data in python?

**Comment by FZambia** [comment]
Hello @patterniha 

Fossil delta compression support has been merged to master just a couple of days ago - it will become available in the next release, I think today or tomorrow.

**Comment by FZambia** [comment]
Mm, btw - need to fix the example before the release, because it was eventually changed to ENUM - https://github.com/centrifugal/centrifuge-python/blob/4795ccfae07d3c02735fffc8b3550499ce2000d8/centrifuge/client.py#L211

```python
client.new_subscription("channel", delta=DeltaType.FOSSIL)
```

**Comment by FZambia** [comment]
Released in https://github.com/centrifugal/centrifuge-python/releases/tag/0.3.1
