### ISSUE TITLE
subscribe to private channels?

### ISSUE THREAD

**Issue by flc** [vovadenisov/centrifuge-python#4]
Hi!
Is it possible to subscribe to private channels with this client?
I have a private channel subscription sign but I don't know how to pass it to client.subscribe.

**Comment by FZambia** [comment]
@flc hello, will add it soon. We have some things non implemented here yet

**Comment by flc** [comment]
nice, thank you for the info!

**Comment by FZambia** [comment]
@flc I just pushed support for this in https://github.com/centrifugal/centrifuge-python/commit/1b0f3234aa748fb1dc1326ff54eb1ad98f5537d3 - there is an example of usage also. But I still can't guarantee that API of this package won't change as it still a work in progress and have no release on PYPI yet. Use with caution

**Comment by flc** [comment]
hello, it seems to work. thank you! no problem if you change the API of course.
