### ISSUE TITLE
Synchronous python client

### ISSUE THREAD

**Issue by synw** [vovadenisov/centrifuge-python#6]
Do you think that a synchronous python client would be possible?

The reason is because I would like to use it in some scenario where asyncio is not an option (in a Django management command).

**Comment by FZambia** [comment]
As far as I know it's possible to start Asyncio loop even inside synchronous code do the work and then stop the loop.

Also I think starting client in thread and communicating with it is also an option. 

But what you want to achieve? A better problem understanding can help me to give a better advice maybe.

**Comment by synw** [comment]
> As far as I know it's possible to start Asyncio loop even inside synchronous code do the work and then stop the loop.

I did not know. I want to use it with Django, which I was convinced that can not run asyncio code

My research goal is to listen to a channel from a Django management command to be able to trigger some kind of rpc calls. I want to make some experiments to see what I could do with it. It could open the door for nice apps where some external services could heavily communicate with Django via Centrifugo without bothering the http server.

I used the concept of command channel in some go research project I have ([code](https://github.com/synw/microb/blob/master/main.go#L58)) where some microservices are driven by a terminal client to manage their state and do stuff

[ Edit ] : in the category of weird ideas and related to this I also have a [research project](https://github.com/synw/django-jobrunner) that is a go process that listens to a channel for jobs and  forwards the information to a django management command ran from a goroutine (via shell script for the python context!). The django management command then sends back the output via a channel to the original client. This is cumbersome and easily racy but fun. 

So I am interested in researching smoothest solutions in python only for these experiments of non idiomatic Centrifugo usages

**Comment by FZambia** [comment]
In general you can do whatever you want inside management command - run asyncio, run many threads and communicate between etc. And as far as I know django-channels v2 for example does some sort of this to add async support to Django.

I am not sure this will result in good design (especially with using Centrifugo for this layer which just was not designed with this in mind and I can't say without researching how it fits this sort of work). What I can say is there are convenient best practices and solutions that do a job. For example Celery for async tasks - it's impossible to change it painlessly without loosing guarantees it gives etc.

**Comment by synw** [comment]
Thanks for your answers. I'll check the Django Channels code, that's a very good idea. The thing is that Asyncio and Twisted are not my cup of tea but it should be interesting to read, thanks for the suggestion.

Anyway these thinks are just wild experiments and I agree that using proper tools like Celery, Rq or Huey is appropriate. 

I feel like Go is much more suitable for the kind of thinks I am trying to do. The new Centrifugo 2 rpc calls should facilitate my progression on some of these weird research tracks that I am on sometimes
