### ISSUE TITLE
possible API mismatch

### ISSUE THREAD

**Issue by vindemasi** [vovadenisov/centrifuge-python#7]
Hello,

I suspect the API is broken here
https://github.com/centrifugal/centrifuge-python/blob/master/centrifuge/client.py#L286
here 
https://fzambia.gitbooks.io/centrifugal/content/mixed/private_channels.html
it seems the payload should be:

`{
    "client": "CLIENT ID",
    "channels": ["$one"]
}`

while in the client

`{
    "client_id": "CLIENT ID",
    "channels": ["$one"]
}`

is sent.

regards

**Comment by FZambia** [comment]
Hello @vindemasi! Thanks for pointing, you are right. Will try to push a fix tomorrow. This is a strange situation when commit with fix will break backwards compatibility but I suppose it's OK for this client  as it was not  released yet..

**Comment by vindemasi** [comment]
Hello @FZambia,
thank you for quick response. In fact is ok, if the client translate the payload before ask to the backend. But the documentation has a sample code using "client"

**Comment by FZambia** [comment]
@vindemasi just pushed a fix, I don't like the fact that I've broken API :( But I hope I can do this for this library as it has no releases yet.
